version: "3"

services:
  clusterone-web:
    build:
      context: .
      dockerfile: DockerFile
    image: clusterone-web
    ports:
      - "3006:8080"
    networks:
      - cluster_one_network
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
    


networks:
  cluster_one_network:
    driver: bridge